version: "3.7"

services:
    # image project
    app:
        container_name: desafio-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: desafio/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        container_name: desafio-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        container_name: desafio-mysql
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel

   

    # redis
    redis:
        container_name: especializati-redis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge